# =============================================================================
# Streamlit Web Application Deployment and Service
# =============================================================================
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: tradingagents-cn
  labels:
    app.kubernetes.io/name: tradingagents-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: tradingagents-platform
spec:
  selector:
    app.kubernetes.io/name: tradingagents-web
  ports:
    - name: http
      port: 8501
      targetPort: 8501
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradingagents-web
  namespace: tradingagents-cn
  labels:
    app.kubernetes.io/name: tradingagents-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: tradingagents-platform
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: tradingagents-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tradingagents-web
        app.kubernetes.io/component: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8501"
        prometheus.io/path: "/_stcore/metrics"
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        fsGroup: 1001
      containers:
        - name: web
          image: your-registry.com/tradingagents-cn-web:latest
          ports:
            - containerPort: 8501
              name: http
          envFrom:
            - configMapRef:
                name: tradingagents-config
            - secretRef:
                name: tradingagents-secrets
          env:
            - name: API_BASE_URL
              value: "http://api-service:8000"
            - name: DISPLAY
              value: ":99"
          volumeMounts:
            - name: app-data
              mountPath: /app/data
            - name: app-logs
              mountPath: /app/logs
            - name: app-reports
              mountPath: /app/reports
            - name: app-config
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data-pvc
        - name: app-logs
          persistentVolumeClaim:
            claimName: app-logs-pvc
        - name: app-reports
          persistentVolumeClaim:
            claimName: app-reports-pvc
        - name: app-config
          persistentVolumeClaim:
            claimName: app-config-pvc
      terminationGracePeriodSeconds: 30
---
# =============================================================================
# Horizontal Pod Autoscaler for Web
# =============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tradingagents-web-hpa
  namespace: tradingagents-cn
  labels:
    app.kubernetes.io/name: tradingagents-web
    app.kubernetes.io/component: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tradingagents-web
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30